// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-fichas.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_fichas_default = defineTool({
  name: "list_fichas",
  title: "Listar fichas t\xE9cnicas",
  description: "Lista las fichas t\xE9cnicas del taller. Permite filtrar por estado (TALLER, ESPERA_REPUESTO, LISTO, ENTREGADA) y limitar la cantidad.",
  inputSchema: {
    estado: z.enum(["TALLER", "ESPERA_REPUESTO", "LISTO", "ENTREGADA"]).optional().describe("Filtrar por estado de la ficha"),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de resultados (por defecto 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("fichas").select("id, numero_boleta, cliente_nombre, modelo_maquina, mecanico, cliente_direccion, fecha_ingreso, fecha_entrega").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (estado) q = q.eq("cliente_direccion", estado);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { fichas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-cliente.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_cliente_default = defineTool2({
  name: "search_cliente",
  title: "Buscar cliente",
  description: "Busca clientes por nombre o tel\xE9fono (coincidencia parcial, may\xFAsculas/min\xFAsculas ignoradas).",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Nombre o tel\xE9fono a buscar")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("clientes").select("id, nombre, telefono, puntos").or(`nombre.ilike.%${query}%,telefono.ilike.%${query}%`).order("nombre").limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clientes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-repuesto.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_repuesto_default = defineTool3({
  name: "search_repuesto",
  title: "Buscar repuesto",
  description: "Busca repuestos por nombre o c\xF3digo (coincidencia parcial). Devuelve c\xF3digo, nombre y precio.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Nombre o c\xF3digo del repuesto")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("repuestos").select("id, codigo, nombre, precio").or(`nombre.ilike.%${query}%,codigo.ilike.%${query}%`).order("nombre").limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { repuestos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-ficha-estado.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_ficha_estado_default = defineTool4({
  name: "update_ficha_estado",
  title: "Actualizar estado de ficha",
  description: "Cambia el estado de una ficha t\xE9cnica. Si el nuevo estado es ENTREGADA, registra la fecha de entrega autom\xE1ticamente.",
  inputSchema: {
    id: z4.string().uuid().describe("ID de la ficha"),
    estado: z4.enum(["TALLER", "ESPERA_REPUESTO", "LISTO", "ENTREGADA"])
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ id, estado }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("fichas").update({
      cliente_direccion: estado,
      fecha_entrega: estado === "ENTREGADA" ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).eq("id", id).select("id, numero_boleta, cliente_direccion, fecha_entrega");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Ficha actualizada: ${JSON.stringify(data?.[0])}` }],
      structuredContent: { ficha: data?.[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bpqqjqeygpqjpykiagtj";
var mcp_default = defineMcp({
  name: "stihl-ancud-mcp",
  title: "STIHL Ancud - Taller",
  version: "0.1.0",
  instructions: "Herramientas del sistema de taller STIHL Ancud. Permite consultar fichas t\xE9cnicas, buscar clientes y repuestos, y actualizar el estado de una ficha (TALLER, ESPERA_REPUESTO, LISTO, ENTREGADA). Todas las operaciones se ejecutan como el usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_fichas_default, search_cliente_default, search_repuesto_default, update_ficha_estado_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
